### ISSUE TITLE
Readme example crashes at spy.close()

### ISSUE THREAD

**Issue by tgecho** [alloc/filespy#5]
I copied and pasted the example into a file as a starting point and got this error
```
[snip]/node_modules/filespy/dist/filespy.js:269
    close: () => watching.then((watcher) => {
                          ^
TypeError: Cannot read property 'then' of undefined
    at Object.close ([snip]/node_modules/filespy/dist/filespy.js:269:27)
    at main ([snip]/bin/test-watcher.js:46:7)
    [snip]
```
Since it has us calling `spy.close()` right at the end of the example, it appears the internal `setImmediate` callback doesn't have a chance to fire before I call `spy.close()`, so the `watching` is still undefined.

The most obvious way I can see to fix this is to ensure `watching` is always a valid promise with something like:
```
const watching = new Promise(resolve => {
  setImmediate(() => {
    resolve(waitForPath.waitForPath( .....
```

Happy to send in a PR to this effect if you want it.

**Comment by aleclarson** [comment]
Is there an actual use case for calling `.close` right after calling `filespy`?

May be better to fix the readme example. 🤔 

If we fixed `.close`, I would prefer to abort the `setImmediate` callback altogether.

**Comment by tgecho** [comment]
That fix makes even more sense! 👍
